#!/bin/sh

hypr=$HOME/.hyprconfig
wallpaper_folder=$hypr/themes/apatheia/wallpapers

wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/themes/apatheia/scripts/wallpaper

# echo "~/.hyprconfig/themes/apatheia/wallpapers$wallpaper"
# swaybg -m fill -i "$HOME/.hyprconfig/themes/apatheia/wallpapers/$wallpaper" &
