#! /bin/sh

hyprctl keyword windowrule "workspace 7 silent,discord" && hyprctl dispatch exec "discord"
hyprctl keyword windowrule "workspace 8 silent,spotify" && hyprctl dispatch exec "spotify"
hyprctl keyword windowrule "workspace 2 silent,google-chrome-stable" && hyprctl dispatch exec "google-chrome-stable"

sleep 15

hyprctl keyword windowrule "unset,discord"
hyprctl keyword windowrule "unset,spotify"
hyprctl keyword windowrule "unset,google-chrome-stable"