#!/usr/bin/bash

# variables
config=$HOME/.hyprconfig
scripts=$config/scripts

# polkit
exec-once=/usr/lib/polkit-kde-authentication-agent-1 &

# notification daemon
dunst &

# screen_sharing 
pipewire &

# launch main apps
$scripts/autolaunch_on_workspace &

# screen locking when idle
$scripts/default/idle_handler &

# effects
$scripts/rgb &

# other
## persistent clipboard
wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &
## make kde connect work  (source: https://www.reddit.com/r/kde/comments/l6t6qu/please_make_kdeconnectcli_work_in_headless_moded/)
/usr/lib/kdeconnectd -platform offscreen &

# launch portals after executing the above
$scripts/default/launch_portals &